# Use the official MySQL image
FROM mysql:latest

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=root123
ENV MYSQL_DATABASE=template
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=root123

# Expose the MySQL port
EXPOSE 3306
