apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: your-storage-class-name
  resources:
    requests:
      storage: 10Gi  # Adjust the size based on your requirements
