---
apiVersion: v1
kind: Service
metadata:
  name: productmicroservice-service
spec:
  selector:
    app: productmicroservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
